In [1]:
import scipy as sc 
import numpy as np 
array1 = np.array ([1 ,2 ,3])
print(array1)

[1 2 3]


In [2]:
array2 = np.linspace ( 0 , 100 , 5)
print(array2 , '\n')
array22 = np.linspace (0 , 25 , 3)
print(array22 , '\n')

[  0.  25.  50.  75. 100.] 

[ 0.  12.5 25. ] 



In [3]:
array3 = np.arange (0 , 125 , 2)
print(array3 , '\n')
array4 = np.arange (0 , 5 , 0.5)
print(array4 , '\n')
array44 = np.arange (0 , 125 , 2)
print(array44 , '\n')

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124] 

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5] 

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124] 



In [5]:
array5 = np.zeros (5)
print(array5 , '\n')
array6 = np.ones (100)
print(array6 , '\n')


[0. 0. 0. 0. 0.] 

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.] 



In [6]:
array7 = np.linspace (-20 , 3 , 12)
print(array7 , '\n')
print(array7 +2 , '\n')
print(array7 -1 , '\n')
print(array7 *3 , '\n')
print(array7 /2 , '\n')
print(array7 **4 , '\n')
print((array7 +2)*5 , '\n')
print(np.sin(array7) , '\n')
print(np.cos(array7) , '\n')

[-20.         -17.90909091 -15.81818182 -13.72727273 -11.63636364
  -9.54545455  -7.45454545  -5.36363636  -3.27272727  -1.18181818
   0.90909091   3.        ] 

[-18.         -15.90909091 -13.81818182 -11.72727273  -9.63636364
  -7.54545455  -5.45454545  -3.36363636  -1.27272727   0.81818182
   2.90909091   5.        ] 

[-21.         -18.90909091 -16.81818182 -14.72727273 -12.63636364
 -10.54545455  -8.45454545  -6.36363636  -4.27272727  -2.18181818
  -0.09090909   2.        ] 

[-60.         -53.72727273 -47.45454545 -41.18181818 -34.90909091
 -28.63636364 -22.36363636 -16.09090909  -9.81818182  -3.54545455
   2.72727273   9.        ] 

[-10.          -8.95454545  -7.90909091  -6.86363636  -5.81818182
  -4.77272727  -3.72727273  -2.68181818  -1.63636364  -0.59090909
   0.45454545   1.5       ] 

[1.60000000e+05 1.02871285e+05 6.26074842e+04 3.55088861e+04
 1.83345028e+04 8.30207124e+03 3.08805246e+03 8.27632061e+02
 1.14720033e+02 1.95075473e+00 6.83013455e-01 8.10000000e+01] 

[-90

In [7]:
array8 = np.array ([10 ,20 ,30])
array9 = np.array ([50 ,60 ,70])
result1 = array8+array9
print(result1 , '\n')
print(array9-array8 , '\n')
print(array8-array9 , '\n')
print(array8*array9 , '\n')
print(array9/array8 , '\n')


[ 60  80 100] 

[40 40 40] 

[-40 -40 -40] 

[ 500 1200 2100] 

[5.         3.         2.33333333] 



In [8]:
array10 = np.array ([[10 ,20 ,30],[50 ,60 ,70]])
print(array10 , '\n')
array11 = np.array ([[111 ,222 ,333],[111 ,222 ,333]])
print(array11 , '\n')

[[10 20 30]
 [50 60 70]] 

[[111 222 333]
 [111 222 333]] 



In [9]:
array12 = np.array ([np.eye(3)])
print(array12 , '\n')


[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]] 



In [22]:
array13 = np.arange(8)
print(array13 ,'\n')
array14 = np.reshape(array13 ,(2 ,4))
print(array14 ,'\n')
print(np.reshape(array13 ,(4 ,2) ,'\n'))
print(np.reshape(np.arange(8) ,(4 ,2)) ,'\n')
print(np.reshape(array13 ,(2 ,5)) ,'\n')

[0 1 2 3 4 5 6 7] 

[[0 1 2 3]
 [4 5 6 7]] 



TypeError: order not understood

In [23]:
array15 = np.array ([[10 ,20 ,30],[15 ,30 ,40]])
print(array15 , '\n')
print(array15+2 , '\n')
print(array15-3 , '\n')
print(array15*5 , '\n')
print(2/array15 , '\n')
print(array15**3 , '\n')
print(np.cos(array15) , '\n')

[[10 20 30]
 [15 30 40]] 

[[12 22 32]
 [17 32 42]] 

[[ 7 17 27]
 [12 27 37]] 

[[ 50 100 150]
 [ 75 150 200]] 

[[0.2        0.1        0.06666667]
 [0.13333333 0.06666667 0.05      ]] 

[[ 1000  8000 27000]
 [ 3375 27000 64000]] 

[[-0.83907153  0.40808206  0.15425145]
 [-0.75968791  0.15425145 -0.66693806]] 



In [24]:
array16 = np.array ([[10. ,20. ,30.],[15. ,30. ,40.]])
print(array16 , '\n')
array17 = np.array ([[-10. ,-20. ,-30.],[-15. ,-30. ,-40.]])
print(array17 , '\n')
array16 * array17

[[10. 20. 30.]
 [15. 30. 40.]] 

[[-10. -20. -30.]
 [-15. -30. -40.]] 



array([[ -100.,  -400.,  -900.],
       [ -225.,  -900., -1600.]])

In [27]:
array18 = sc.rand(8)
print(np.array(np.reshape((array18) ,(2 ,4))) ,'\n')
array19 = print(np.array(np.reshape((sc.rand(8)) ,(2 ,4))) ,'\n')


[[0.6937925  0.7438618  0.36655186 0.00779701]
 [0.0459762  0.42514596 0.09885575 0.21779286]] 

[[0.99866405 0.1355933  0.6836632  0.93144697]
 [0.49865718 0.31587864 0.75094746 0.77479596]] 

